modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/ochotonida/trofers/issues"
license="MIT"

[[mods]]
modId = "trofers"
version = "1.17.1-2.4.0"
displayName = "Trofers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/trofers"
logoFile = "logo.png"
description = '''Adds customizable trophies'''

[[dependencies.trofers]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.trofers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"